import jsPDF from 'jspdf';
import html2canvas from 'html2canvas-pro';

const FOOTER = 'Generated by ArthSaathi — ET AI Hackathon 2026';

/**
 * Rasterizes the report DOM to PNG (sharp text) and tiles it across A4 pages.
 * Caller must expand collapsibles / print layout before invoking.
 */
export async function exportReportPdf(element: HTMLElement, investorName: string): Promise<void> {
  await new Promise((r) => setTimeout(r, 2000));

  const scrollW = Math.ceil(Math.max(element.scrollWidth, element.clientWidth));
  const scrollH = Math.ceil(element.scrollHeight);

  const canvas = await html2canvas(element, {
    scale: 2.25,
    useCORS: true,
    allowTaint: true,
    backgroundColor: '#0f1117',
    logging: false,
    width: scrollW,
    height: scrollH,
    windowWidth: scrollW,
    windowHeight: scrollH,
    x: 0,
    y: 0,
    scrollX: 0,
    scrollY: 0,
  });

  const imgData = canvas.toDataURL('image/png');

  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 10;
  const innerW = pageWidth - margin * 2;
  const innerH = pageHeight - margin * 2;

  /** Full image height in mm when fitted to page width (preserve aspect ratio). */
  const imgHFullMm = (canvas.height * innerW) / canvas.width;
  let yMm = 0;
  let page = 0;

  while (yMm < imgHFullMm - 0.5) {
    if (page > 0) pdf.addPage();
    pdf.addImage(imgData, 'PNG', margin, margin - yMm, innerW, imgHFullMm);
    yMm += innerH;
    page += 1;
  }

  pdf.setFontSize(8);
  pdf.setTextColor(160, 165, 175);
  const total = pdf.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    pdf.setPage(i);
    pdf.text(FOOTER, margin, pageHeight - 4);
  }

  const date = new Date().toISOString().slice(0, 10);
  const safeName = investorName.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 20);
  pdf.save(`ArthSaathi_${safeName}_${date}.pdf`);
}
